### ISSUE TITLE
Suggestion: Change the e-mail provider to one that takes data protection in Europe seriously.

### ISSUE THREAD

**Issue by linux-lukas** [merlinschumacher/merlinschumacher#2]
In view of the fact that Google reads all emails (see https://www.kuketz-blog.de/gmail-google-liest-eure-e-mails-mit/), I would like to suggest whether it would be possible to use an email provider that complies with data protection in Europe (DSGVO).

E.g. 

1. posteo
2. mailbox
3. tutanota

In addition, a public OpenPGP key including fingerprint would certainly not be wrong either.

**Comment by merlinschumacher** [comment]
Stop with the evangelism.
